# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0
---
name: sdk-release-python

on:
  push:
    tags:
      - "v*" # Only trigger on tag push (created by release-please)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-sdk-wheel:
    name: SDK Python wheel
    uses: ./.github/workflows/reusable-python-build-wheel.yaml

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs:
      - build-sdk-wheel
    if: needs.build-sdk-wheel.result == 'success'
    environment: pypi
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: ./dist

      - name: Show files
        run: ls -l ./dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: ./dist
